waku-org/docs.waku.org

.cspell.json, static/discv5.md, static/dns_discovery.md, static/peer_exchange.md
Ref  #7 tackling:
> (1) Message flow architecture diagram:
- Shows Waku Relay and pubsub topic message routing
- Shows Filter/Light Push/Store usage with content topic usage/filtering.
- could include information about transports used (tcp, websocket) if does not make it too busy
- Include adaptive node information: cloud vs laptop (native) vs mobile vs browser
>  (2) architecture diagram of Discovery: DNS Discovery + Discv5 + peer exchange + peer persistence
Review tip: click "view file" to have GitHub render the mermaid code.
=> add network diagram

docs/guides/nodes-and-sdks.md, docs/guides/nwaku/run-docker-compose.md, docs/guides/nwaku/run-docker.md
This PR:
- removes references to `alreavuelta/nwaku-compose` in favour of `waku-org/nwaku-compose`
- removes reference to `latest` image tag as that is not currently updated in registry (will add it back when fixed)
-  updates the nwaku-compose guide with how to configure the options
- pins the Docker guide `docker run` command to a last releast tag
=> chore: update nwaku docker and compose docs

.cspell.json, docs/guides/nwaku/build-source.md
Adds `rustup` to the dependencies since `rln` is no longer experimental - thanks @gabrielmer
=> chore(docs): add rustup to the installation prerequisites

docs/guides/nwaku/configure-discovery.md, docs/guides/nwaku/run-docker.md
Enrtrees were regenerated. Need to update the old one.
DNS discoverty should continue to work.
=> update wakuv2 fleet DNS discovery enrtree

.cspell.json, docs/guides/nwaku/configure-nwaku.md
letsencrypt only work if a webserver is installed. We can assume if someone installed a webserver, they know what they are doing.
Someone just using the docker-compose needs certbot
=> Use certbot certonly

docs/guides/nwaku/run-docker-compose.md
The naming was confusing to hackers wanting to run a node, changed it to reflect the private key.
=> fix: testnet key naming and add timestamp to sample message send

docs/guides/js-waku/index.md, docs/guides/js-waku/light-send-receive.md, docs/guides/js-waku/manage-filter.md, docs/guides/js-waku/message-encryption.md, docs/guides/js-waku/use-waku-react.md, docs/learn/glossary.md, docs/learn/waku-network.md, docusaurus.config.js, sidebars.js
Tackles some of the tasks in https://github.com/waku-org/docs.waku.org/issues/125
preview: https://docs-waku-org-git-js-encryption-acidinfo.vercel.app/guides/js-waku/message-encryption
pending:
=> add js-waku encryption guide

docs/rules-of-engagement.md, docusaurus.config.js
Adds the "Rules of Engagement" article and resolves https://github.com/waku-org/docs.waku.org/issues/177
Preview: https://docs-waku-org-git-add-rules-of-engagement-acidinfo.vercel.app/rules-of-engagement
=> add rules of engagement article

docs/guides/nwaku/run-docker-compose.md, docusaurus.config.js
Resolves https://github.com/waku-org/docs.waku.org/issues/195 and https://github.com/waku-org/docs.waku.org/issues/196
=> add all the community links

docs/guides/nwaku/config-options.md
It was a leftover after removing legacy filter feature where it belong to.
=> chore: As legacy filter is retired we don't have filter-timeout config flag anymore

docs/guides/nwaku/run-docker.md
This PR is needed to avoid confusion for node operators and properly differentiate the "get Docker image" from "build Docker image".
=> run-docker clarify title

docs/learn/faq.md
Adding a new point to refer the nwaku-compose repo. From there, node operators should be able to get the node's FAQ
https://github.com/waku-org/nwaku-compose/pull/120
=> extending faq adding how to run a node point

docs/guides/nwaku/migrate-version.md, docs/guides/nwaku/upgrade-instructions.md, sidebars.js
Adding section with instructions on how to migrate a node after new releases
=> feat: add migration instructions

docs/research/index.md
Added links to currently published research papers by Vac/Waku.
Note that the Waku Infrastructure paper does not yet have an open-access version (e.g. arxiv.org). Will update the link once we do.
=> docs: add links to published research papers.md

docs/guides/js-waku/configure-discovery.md
This PR is follow up to https://github.com/waku-org/js-waku/pull/2103
=> chore: update docs to show new property

docs/guides/js-waku/configure-discovery.md, docs/learn/faq.md, docs/learn/research.md, docs/learn/security-features.md, docs/learn/waku-network.md, docs/privacy-policy.md, docs/research/research-and-studies/maximum-bandwidth.md
Fixes #207 
Corrected several grammatical errors in the documentation to improve clarity and readability. No changes were made to the structure or meaning of the text. The content remains consistent with the original intent, ensuring that the documentation is now more polished while preserving its original format and structure.
=> Fixed grammatical errors in documentation

docs/guides/nwaku/config-options.md
Adding `num-shards-in-network` option to our config docs
=> Adding num-shards-in-network config option to documentation

docs/guides/getting-started.md, docs/guides/js-waku/use-waku-react.md, docs/learn/waku-network.md
All links pointing to blog.waku.org seem to be broken leading to 404.
Updated relevant links to correct working ones.
=> fix: broken links to blog.waku.org

docs/guides/nwaku/config-options.md
Removing the deprecated `protected-topic` config in favor of `protected-shard`
=> chore: updating protected topics in favor of protected shards

docs/guides/nwaku/build-source.md
[nwaku had a long recorded issue building from source on Fedora Linux.](https://github.com/waku-org/nwaku/issues/2087)
Thanks to @Ivansete-status it is revealed that the only issue is that nimbus build system rely on `which` utility that is not part of the distro out of the box. Installing it fixes the issue, hence mentioning in the build guide.
=> chore: Add which utility as pre-req for fedora build guidance

docs/guides/nwaku/config-options.md
The waku network no longer requires a local rln_tree for syncing the current state. It now relies on the smart contract, so the `rln-relay-tree-path` config is no longer needed.
=> chore: depr rln-relay-tree-path
