waku-org/docs.waku.org

docs/community.md, docs/contribute.md, docs/getting-started/concepts/content-topics.md, docs/getting-started/concepts/network-domains.md, docs/getting-started/concepts/peer-discovery.md, docs/getting-started/concepts/protocols.md, docs/getting-started/concepts/transports.md, docs/getting-started/index.md, docs/getting-started/reference/glossary.md, docs/getting-started/reference/research-in-progress.md, docs/guides/sdks-and-nodes.md, sidebars.js, static/custom.css
TL;DR of what happened:
- implemented feedback from #53
- add glossary content
- add content topic name considerations
=> #53 feedback + add glossary

docusaurus.config.js, package.json, yarn.lock
TBD:
1. https://fathom.status.im/tracker.js  Is this link valid?
2. Can I get the fathom siteId for docs.waku.org?
=> feat: implement fathom

.cspell.json, docs/guides/nodes-and-sdks.md, docs/guides/nwaku/build-source.md, docs/guides/reference/node-config-options.md, docs/powered-by-waku.mdx, docusaurus.config.js
=> add libpq pre-req

docs/guides/nwaku/configure-discovery.md, docs/guides/nwaku/run-docker.md, docs/guides/run-nwaku-node.md, docs/overview/concepts/peer-exchange.md
=> add peer exchange nwaku config

.cspell.json, docs/guides/js-waku/configure-discovery.md, docs/guides/js-waku/debug-waku-dapp.md, docs/guides/js-waku/index.md, docs/guides/js-waku/run-waku-nodejs.md, docs/guides/reference/node-config-options.md, sidebars.js
Addresses the `js-waku` debug and NodeJS tasks on #104
=> add js-waku debug guide

.cspell.json, docs/guides/js-waku/light-send-receive.md, docs/guides/nwaku/build-source.md, docs/guides/nwaku/configure-nwaku.md, docs/guides/nwaku/run-docker-compose.md, docs/guides/nwaku/run-docker.md, docs/guides/reference/node-config-options.md, docs/guides/run-nwaku-node.md, docs/overview/reference/glossary.md, sidebars.js
=> nwaku config guides

docs/terms.md
Update the terms content as per request.
This update should be applied to the master branch also.
=> Terms update

.cspell.json, diagrams/_filter-ping-flow.md, docs/guides/js-waku/debug-waku-dapp.md, docs/guides/js-waku/index.md, docs/guides/js-waku/light-send-receive.md, docs/guides/js-waku/manage-filter.md, docs/guides/nwaku/configure-nwaku.md, sidebars.js
Tackles documenting peer disconnection: https://github.com/waku-org/docs.waku.org/issues/104#issuecomment-1759113733
Filter ping diagram: https://github.com/waku-org/docs.waku.org/blob/a060043bfbfb5af1c8eddcbd97d07b83e1c505ab/diagrams/_filter-ping-flow.md
=> add manage filter guide

docusaurus.config.js
Fix https://github.com/waku-org/docs.waku.org/issues/135
=> Add light mode back

docs/learn/concepts/content-topics.md
Tackles https://github.com/waku-org/docs.waku.org/issues/146
=> update content topic considerations

docs/guides/getting-started.md, docs/learn/concepts/content-topics.md
adds the buckets consideration: https://github.com/waku-org/docs.waku.org/issues/146#issuecomment-1846937213
preview: https://docs-waku-org-git-content-topics-buckets-acidinfo.vercel.app/learn/concepts/content-topics#creating-buckets-help-in-distributing-traffic
=> add content topic buckets consideration

docs/guides/nwaku/run-docker-compose.md, docs/guides/nwaku/run-node.md
Updates the Docker Compose guides and recommends it as the fastest way to get started: https://github.com/waku-org/docs.waku.org/issues/154
=> update nwaku compose

docs/guides/nwaku/config-options.md
In relation to https://github.com/waku-org/nwaku/pull/2341
Notice nwaku change will take place with 0.25.0 or 0.24.1 release (not in the upcoming 0.24.0).
=> Add new filter conifguration argument

.cspell.json, docs/guides/js-waku/faq.md, docs/guides/js-waku/light-send-receive.md, docs/guides/js-waku/message-encryption.md, docs/guides/js-waku/run-waku-nodejs.md, docs/guides/js-waku/use-waku-react.md, docs/guides/nwaku/configure-nwaku.md, docs/guides/nwaku/faq.md, docs/guides/nwaku/faq.mdx, docs/guides/nwaku/run-node.md, package.json, sidebars.js, yarn.lock
Resolves the FAQ task of https://github.com/waku-org/docs.waku.org/issues/152
Preview:
- https://docs-waku-org-git-add-faq-acidinfo.vercel.app/guides/nwaku/faq
- https://docs-waku-org-git-add-faq-acidinfo.vercel.app/guides/js-waku/faq
=> add FAQ sections for nwaku and js-waku docs

docs/guides/js-waku/configure-discovery.md, docs/guides/js-waku/light-send-receive.md, docs/guides/js-waku/message-encryption.md
This PR is a follow-up to https://github.com/waku-org/js-waku/pull/1871 with mention of a better API to get static peers bootstrapped.
=> chore: update doc for setting static peers

docs/guides/nwaku/configure-discovery.md, docs/guides/nwaku/configure-nwaku.md, docs/guides/nwaku/run-docker.md
See https://github.com/status-im/infra-nim-waku/issues/91 for details
Mostly done automatically. Some parts manually.
=> chore: switch wakuv2 fleet to waku

docs/security.md
Update the HackenProof link as per request
=> Update security page link

docs/guides/js-waku/light-send-receive.md, docs/guides/js-waku/manage-filter.md
This PR updates docs for Filter subscription to show new API.
Resolves - https://github.com/waku-org/js-waku/issues/2022
=> chore: update Filter API

docs/research/benchmarks/test-results-summary.md
This PR is to update the content of the repo by committing the changes from the docs directory of the nwaku repo.
The addition from this commit https://github.com/waku-org/nwaku/commit/94554a6e02862a638926ba3d02d7464b3fdd491f is being added here.
=> Add new benchmarks subpage - test-reports-summary

.cspell.json, docs/guides/nwaku/config-options.md, docs/guides/nwaku/configure-nwaku.md
=> feat: add store sync entrees
